export const OPEN_TEXT = 'OPEN_TEXT';
export const CHANGE_ORDER_ELEMENTS = 'CHANGE_ORDER_ELEMENTS';
export const IS_READ_ARTICLE = 'IS_READ_ARTICLE';
export const SAVED_NUMBER_SELECTED_ARTICLE = 'SAVED_NUMBER_SELECTED_ARTICLE';
export const GRANT_ACCESS_TO_USER = 'GRANT_ACCESS_TO_USER';
export const DENY_USER_ACCESS = 'DENY_USER_ACCESS';